[[main]]
none = "none"

[[main]]
name = "Events"
pageRef = "Events"
identifier = "MU5KHCnt3x"
weight = 9997

[[main]]
name = "Tickets"
pageRef = "Tickets"
identifier = "MU5KHCnt3z"
weight = 9998

[[main]]
name = "About Us"
pageRef = "About"
identifier = "MU5KHCnt3y"
weight = 9999

[[footer]]
none = "none"
