name: Deploy Dev Site

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Deploy to dev repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.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 }}
          external_repository: nickcalamaro/GibCardShow-dev
          publish_branch: gh-pages
          publish_dir: ./public
